// countries.ts
export interface Country {
    name: string;
    code: string; // ISO 3166-1 alpha-2 code
    flag: string; // image URL
    wikidataId: string; // Wikidata Q-ID, e.g. 'Q30' for United States
}

export const countries: Country[] = [
    { name: "Afghanistan", code: "af", flag: "https://flagcdn.com/w320/af.png", wikidataId: "Q889" },
    { name: "Albania", code: "al", flag: "https://flagcdn.com/w320/al.png", wikidataId: "Q222" },
    { name: "Algeria", code: "dz", flag: "https://flagcdn.com/w320/dz.png", wikidataId: "Q262" },
    { name: "American Samoa", code: "as", flag: "https://flagcdn.com/w320/as.png", wikidataId: "Q16641" },
    { name: "Andorra", code: "ad", flag: "https://flagcdn.com/w320/ad.png", wikidataId: "Q228" },
    { name: "Angola", code: "ao", flag: "https://flagcdn.com/w320/ao.png", wikidataId: "Q916" },
    { name: "Anguilla", code: "ai", flag: "https://flagcdn.com/w320/ai.png", wikidataId: "Q25228" },
    { name: "Antarctica", code: "aq", flag: "https://flagcdn.com/w320/aq.png", wikidataId: "Q51" },
    { name: "Antigua and Barbuda", code: "ag", flag: "https://flagcdn.com/w320/ag.png", wikidataId: "Q781" },
    { name: "Argentina", code: "ar", flag: "https://flagcdn.com/w320/ar.png", wikidataId: "Q414" },
    { name: "Armenia", code: "am", flag: "https://flagcdn.com/w320/am.png", wikidataId: "Q399" },
    { name: "Aruba", code: "aw", flag: "https://flagcdn.com/w320/aw.png", wikidataId: "Q21203" },
    { name: "Australia", code: "au", flag: "https://flagcdn.com/w320/au.png", wikidataId: "Q408" },
    { name: "Austria", code: "at", flag: "https://flagcdn.com/w320/at.png", wikidataId: "Q40" },
    { name: "Azerbaijan", code: "az", flag: "https://flagcdn.com/w320/az.png", wikidataId: "Q227" },
    { name: "Bahamas", code: "bs", flag: "https://flagcdn.com/w320/bs.png", wikidataId: "Q778" },
    { name: "Bahrain", code: "bh", flag: "https://flagcdn.com/w320/bh.png", wikidataId: "Q398" },
    { name: "Bangladesh", code: "bd", flag: "https://flagcdn.com/w320/bd.png", wikidataId: "Q902" },
    { name: "Barbados", code: "bb", flag: "https://flagcdn.com/w320/bb.png", wikidataId: "Q244" },
    { name: "Belarus", code: "by", flag: "https://flagcdn.com/w320/by.png", wikidataId: "Q184" },
    { name: "Belgium", code: "be", flag: "https://flagcdn.com/w320/be.png", wikidataId: "Q31" },
    { name: "Belize", code: "bz", flag: "https://flagcdn.com/w320/bz.png", wikidataId: "Q242" },
    { name: "Benin", code: "bj", flag: "https://flagcdn.com/w320/bj.png", wikidataId: "Q962" },
    { name: "Bermuda", code: "bm", flag: "https://flagcdn.com/w320/bm.png", wikidataId: "Q23635" },
    { name: "Bhutan", code: "bt", flag: "https://flagcdn.com/w320/bt.png", wikidataId: "Q917" },
    { name: "Bolivia", code: "bo", flag: "https://flagcdn.com/w320/bo.png", wikidataId: "Q750" },
    { name: "Bonaire, Sint Eustatius and Saba", code: "bq", flag: "https://flagcdn.com/w320/bq.png", wikidataId: "Q27561" },
    { name: "Bosnia and Herzegovina", code: "ba", flag: "https://flagcdn.com/w320/ba.png", wikidataId: "Q225" },
    { name: "Botswana", code: "bw", flag: "https://flagcdn.com/w320/bw.png", wikidataId: "Q963" },
    { name: "Bouvet Island", code: "bv", flag: "https://flagcdn.com/w320/bv.png", wikidataId: "Q23408" },
    { name: "Brazil", code: "br", flag: "https://flagcdn.com/w320/br.png", wikidataId: "Q155" },
    { name: "British Indian Ocean Territory", code: "io", flag: "https://flagcdn.com/w320/io.png", wikidataId: "Q43448" },
    { name: "Brunei Darussalam", code: "bn", flag: "https://flagcdn.com/w320/bn.png", wikidataId: "Q921" },
    { name: "Bulgaria", code: "bg", flag: "https://flagcdn.com/w320/bg.png", wikidataId: "Q219" },
    { name: "Burkina Faso", code: "bf", flag: "https://flagcdn.com/w320/bf.png", wikidataId: "Q965" },
    { name: "Burundi", code: "bi", flag: "https://flagcdn.com/w320/bi.png", wikidataId: "Q967" },
    { name: "Cabo Verde", code: "cv", flag: "https://flagcdn.com/w320/cv.png", wikidataId: "Q1011" },
    { name: "Cambodia", code: "kh", flag: "https://flagcdn.com/w320/kh.png", wikidataId: "Q424" },
    { name: "Cameroon", code: "cm", flag: "https://flagcdn.com/w320/cm.png", wikidataId: "Q1009" },
    { name: "Canada", code: "ca", flag: "https://flagcdn.com/w320/ca.png", wikidataId: "Q16" },
    { name: "Cayman Islands", code: "ky", flag: "https://flagcdn.com/w320/ky.png", wikidataId: "Q5785" },
    { name: "Central African Republic", code: "cf", flag: "https://flagcdn.com/w320/cf.png", wikidataId: "Q929" },
    { name: "Chad", code: "td", flag: "https://flagcdn.com/w320/td.png", wikidataId: "Q657" },
    { name: "Chile", code: "cl", flag: "https://flagcdn.com/w320/cl.png", wikidataId: "Q298" },
    { name: "China", code: "cn", flag: "https://flagcdn.com/w320/cn.png", wikidataId: "Q148" },
    { name: "Christmas Island", code: "cx", flag: "https://flagcdn.com/w320/cx.png", wikidataId: "Q31063" },
    { name: "Cocos (Keeling) Islands", code: "cc", flag: "https://flagcdn.com/w320/cc.png", wikidataId: "Q36004" },
    { name: "Colombia", code: "co", flag: "https://flagcdn.com/w320/co.png", wikidataId: "Q739" },
    { name: "Comoros", code: "km", flag: "https://flagcdn.com/w320/km.png", wikidataId: "Q970" },
    { name: "Congo", code: "cg", flag: "https://flagcdn.com/w320/cg.png", wikidataId: "Q971" },
    { name: "Congo, The Democratic Republic of the", code: "cd", flag: "https://flagcdn.com/w320/cd.png", wikidataId: "Q974" },
    { name: "Cook Islands", code: "ck", flag: "https://flagcdn.com/w320/ck.png", wikidataId: "Q26988" },
    { name: "Costa Rica", code: "cr", flag: "https://flagcdn.com/w320/cr.png", wikidataId: "Q800" },
    { name: "Croatia", code: "hr", flag: "https://flagcdn.com/w320/hr.png", wikidataId: "Q224" },
    { name: "Cuba", code: "cu", flag: "https://flagcdn.com/w320/cu.png", wikidataId: "Q241" },
    { name: "Curaçao", code: "cw", flag: "https://flagcdn.com/w320/cw.png", wikidataId: "Q25279" },
    { name: "Cyprus", code: "cy", flag: "https://flagcdn.com/w320/cy.png", wikidataId: "Q229" },
    { name: "Czechia", code: "cz", flag: "https://flagcdn.com/w320/cz.png", wikidataId: "Q213" },
    { name: "Côte d'Ivoire", code: "ci", flag: "https://flagcdn.com/w320/ci.png", wikidataId: "Q1008" },
    { name: "Denmark", code: "dk", flag: "https://flagcdn.com/w320/dk.png", wikidataId: "Q35" },
    { name: "Djibouti", code: "dj", flag: "https://flagcdn.com/w320/dj.png", wikidataId: "Q977" },
    { name: "Dominica", code: "dm", flag: "https://flagcdn.com/w320/dm.png", wikidataId: "Q784" },
    { name: "Dominican Republic", code: "do", flag: "https://flagcdn.com/w320/do.png", wikidataId: "Q786" },
    { name: "Ecuador", code: "ec", flag: "https://flagcdn.com/w320/ec.png", wikidataId: "Q736" },
    { name: "Egypt", code: "eg", flag: "https://flagcdn.com/w320/eg.png", wikidataId: "Q79" },
    { name: "El Salvador", code: "sv", flag: "https://flagcdn.com/w320/sv.png", wikidataId: "Q792" },
    { name: "Equatorial Guinea", code: "gq", flag: "https://flagcdn.com/w320/gq.png", wikidataId: "Q983" },
    { name: "Eritrea", code: "er", flag: "https://flagcdn.com/w320/er.png", wikidataId: "Q986" },
    { name: "Estonia", code: "ee", flag: "https://flagcdn.com/w320/ee.png", wikidataId: "Q191" },
    { name: "Eswatini", code: "sz", flag: "https://flagcdn.com/w320/sz.png", wikidataId: "Q1050" },
    { name: "Ethiopia", code: "et", flag: "https://flagcdn.com/w320/et.png", wikidataId: "Q115" },
    { name: "Falkland Islands (Malvinas)", code: "fk", flag: "https://flagcdn.com/w320/fk.png", wikidataId: "Q9648" },
    { name: "Faroe Islands", code: "fo", flag: "https://flagcdn.com/w320/fo.png", wikidataId: "Q4628" },
    { name: "Fiji", code: "fj", flag: "https://flagcdn.com/w320/fj.png", wikidataId: "Q712" },
    { name: "Finland", code: "fi", flag: "https://flagcdn.com/w320/fi.png", wikidataId: "Q33" },
    { name: "France", code: "fr", flag: "https://flagcdn.com/w320/fr.png", wikidataId: "Q142" },
    { name: "French Guiana", code: "gf", flag: "https://flagcdn.com/w320/gf.png", wikidataId: "Q3769" },
    { name: "French Polynesia", code: "pf", flag: "https://flagcdn.com/w320/pf.png", wikidataId: "Q30971" },
    { name: "French Southern Territories", code: "tf", flag: "https://flagcdn.com/w320/tf.png", wikidataId: "Q129003" },
    { name: "Gabon", code: "ga", flag: "https://flagcdn.com/w320/ga.png", wikidataId: "Q1000" },
    { name: "Gambia", code: "gm", flag: "https://flagcdn.com/w320/gm.png", wikidataId: "Q1005" },
    { name: "Georgia", code: "ge", flag: "https://flagcdn.com/w320/ge.png", wikidataId: "Q230" },
    { name: "Germany", code: "de", flag: "https://flagcdn.com/w320/de.png", wikidataId: "Q183" },
    { name: "Ghana", code: "gh", flag: "https://flagcdn.com/w320/gh.png", wikidataId: "Q117" },
    { name: "Gibraltar", code: "gi", flag: "https://flagcdn.com/w320/gi.png", wikidataId: "Q1410" },
    { name: "Greece", code: "gr", flag: "https://flagcdn.com/w320/gr.png", wikidataId: "Q41" },
    { name: "Greenland", code: "gl", flag: "https://flagcdn.com/w320/gl.png", wikidataId: "Q223" },
    { name: "Grenada", code: "gd", flag: "https://flagcdn.com/w320/gd.png", wikidataId: "Q769" },
    { name: "Guadeloupe", code: "gp", flag: "https://flagcdn.com/w320/gp.png", wikidataId: "Q17012" },
    { name: "Guam", code: "gu", flag: "https://flagcdn.com/w320/gu.png", wikidataId: "Q16635" },
    { name: "Guatemala", code: "gt", flag: "https://flagcdn.com/w320/gt.png", wikidataId: "Q774" },
    { name: "Guernsey", code: "gg", flag: "https://flagcdn.com/w320/gg.png", wikidataId: "Q25230" },
    { name: "Guinea", code: "gn", flag: "https://flagcdn.com/w320/gn.png", wikidataId: "Q1006" },
    { name: "Guinea-Bissau", code: "gw", flag: "https://flagcdn.com/w320/gw.png", wikidataId: "Q1007" },
    { name: "Guyana", code: "gy", flag: "https://flagcdn.com/w320/gy.png", wikidataId: "Q734" },
    { name: "Haiti", code: "ht", flag: "https://flagcdn.com/w320/ht.png", wikidataId: "Q790" },
    { name: "Heard Island and McDonald Islands", code: "hm", flag: "https://flagcdn.com/w320/hm.png", wikidataId: "Q131198" },
    { name: "Holy See (Vatican City State)", code: "va", flag: "https://flagcdn.com/w320/va.png", wikidataId: "Q237" },
    { name: "Honduras", code: "hn", flag: "https://flagcdn.com/w320/hn.png", wikidataId: "Q783" },
    { name: "Hong Kong", code: "hk", flag: "https://flagcdn.com/w320/hk.png", wikidataId: "Q8646" },
    { name: "Hungary", code: "hu", flag: "https://flagcdn.com/w320/hu.png", wikidataId: "Q28" },
    { name: "Iceland", code: "is", flag: "https://flagcdn.com/w320/is.png", wikidataId: "Q189" },
    { name: "India", code: "in", flag: "https://flagcdn.com/w320/in.png", wikidataId: "Q668" },
    { name: "Indonesia", code: "id", flag: "https://flagcdn.com/w320/id.png", wikidataId: "Q252" },
    { name: "Iran", code: "ir", flag: "https://flagcdn.com/w320/ir.png", wikidataId: "Q794" },
    { name: "Iraq", code: "iq", flag: "https://flagcdn.com/w320/iq.png", wikidataId: "Q796" },
    { name: "Ireland", code: "ie", flag: "https://flagcdn.com/w320/ie.png", wikidataId: "Q27" },
    { name: "Isle of Man", code: "im", flag: "https://flagcdn.com/w320/im.png", wikidataId: "Q9676" },
    { name: "Israel", code: "il", flag: "https://flagcdn.com/w320/il.png", wikidataId: "Q801" },
    { name: "Italy", code: "it", flag: "https://flagcdn.com/w320/it.png", wikidataId: "Q38" },
    { name: "Jamaica", code: "jm", flag: "https://flagcdn.com/w320/jm.png", wikidataId: "Q766" },
    { name: "Japan", code: "jp", flag: "https://flagcdn.com/w320/jp.png", wikidataId: "Q17" },
    { name: "Jersey", code: "je", flag: "https://flagcdn.com/w320/je.png", wikidataId: "Q785" },
    { name: "Jordan", code: "jo", flag: "https://flagcdn.com/w320/jo.png", wikidataId: "Q810" },
    { name: "Kazakhstan", code: "kz", flag: "https://flagcdn.com/w320/kz.png", wikidataId: "Q232" },
    { name: "Kenya", code: "ke", flag: "https://flagcdn.com/w320/ke.png", wikidataId: "Q114" },
    { name: "Kiribati", code: "ki", flag: "https://flagcdn.com/w320/ki.png", wikidataId: "Q710" },
    { name: "Kuwait", code: "kw", flag: "https://flagcdn.com/w320/kw.png", wikidataId: "Q817" },
    { name: "Kyrgyzstan", code: "kg", flag: "https://flagcdn.com/w320/kg.png", wikidataId: "Q813" },
    { name: "Laos", code: "la", flag: "https://flagcdn.com/w320/la.png", wikidataId: "Q819" },
    { name: "Latvia", code: "lv", flag: "https://flagcdn.com/w320/lv.png", wikidataId: "Q211" },
    { name: "Lebanon", code: "lb", flag: "https://flagcdn.com/w320/lb.png", wikidataId: "Q822" },
    { name: "Lesotho", code: "ls", flag: "https://flagcdn.com/w320/ls.png", wikidataId: "Q1013" },
    { name: "Liberia", code: "lr", flag: "https://flagcdn.com/w320/lr.png", wikidataId: "Q1014" },
    { name: "Libya", code: "ly", flag: "https://flagcdn.com/w320/ly.png", wikidataId: "Q1016" },
    { name: "Liechtenstein", code: "li", flag: "https://flagcdn.com/w320/li.png", wikidataId: "Q347" },
    { name: "Lithuania", code: "lt", flag: "https://flagcdn.com/w320/lt.png", wikidataId: "Q37" },
    { name: "Luxembourg", code: "lu", flag: "https://flagcdn.com/w320/lu.png", wikidataId: "Q32" },
    { name: "Macao", code: "mo", flag: "https://flagcdn.com/w320/mo.png", wikidataId: "Q14773" },
    { name: "Madagascar", code: "mg", flag: "https://flagcdn.com/w320/mg.png", wikidataId: "Q1019" },
    { name: "Malawi", code: "mw", flag: "https://flagcdn.com/w320/mw.png", wikidataId: "Q1020" },
    { name: "Malaysia", code: "my", flag: "https://flagcdn.com/w320/my.png", wikidataId: "Q833" },
    { name: "Maldives", code: "mv", flag: "https://flagcdn.com/w320/mv.png", wikidataId: "Q826" },
    { name: "Mali", code: "ml", flag: "https://flagcdn.com/w320/ml.png", wikidataId: "Q912" },
    { name: "Malta", code: "mt", flag: "https://flagcdn.com/w320/mt.png", wikidataId: "Q233" },
    { name: "Marshall Islands", code: "mh", flag: "https://flagcdn.com/w320/mh.png", wikidataId: "Q709" },
    { name: "Martinique", code: "mq", flag: "https://flagcdn.com/w320/mq.png", wikidataId: "Q17054" },
    { name: "Mauritania", code: "mr", flag: "https://flagcdn.com/w320/mr.png", wikidataId: "Q1025" },
    { name: "Mauritius", code: "mu", flag: "https://flagcdn.com/w320/mu.png", wikidataId: "Q1027" },
    { name: "Mayotte", code: "yt", flag: "https://flagcdn.com/w320/yt.png", wikidataId: "Q17063" },
    { name: "Mexico", code: "mx", flag: "https://flagcdn.com/w320/mx.png", wikidataId: "Q96" },
    { name: "Micronesia, Federated States of", code: "fm", flag: "https://flagcdn.com/w320/fm.png", wikidataId: "Q702" },
    { name: "Moldova", code: "md", flag: "https://flagcdn.com/w320/md.png", wikidataId: "Q217" },
    { name: "Monaco", code: "mc", flag: "https://flagcdn.com/w320/mc.png", wikidataId: "Q235" },
    { name: "Mongolia", code: "mn", flag: "https://flagcdn.com/w320/mn.png", wikidataId: "Q711" },
    { name: "Montenegro", code: "me", flag: "https://flagcdn.com/w320/me.png", wikidataId: "Q236" },
    { name: "Montserrat", code: "ms", flag: "https://flagcdn.com/w320/ms.png", wikidataId: "Q13353" },
    { name: "Morocco", code: "ma", flag: "https://flagcdn.com/w320/ma.png", wikidataId: "Q1028" },
    { name: "Mozambique", code: "mz", flag: "https://flagcdn.com/w320/mz.png", wikidataId: "Q1029" },
    { name: "Myanmar", code: "mm", flag: "https://flagcdn.com/w320/mm.png", wikidataId: "Q836" },
    { name: "Namibia", code: "na", flag: "https://flagcdn.com/w320/na.png", wikidataId: "Q1030" },
    { name: "Nauru", code: "nr", flag: "https://flagcdn.com/w320/nr.png", wikidataId: "Q697" },
    { name: "Nepal", code: "np", flag: "https://flagcdn.com/w320/np.png", wikidataId: "Q837" },
    { name: "Netherlands", code: "nl", flag: "https://flagcdn.com/w320/nl.png", wikidataId: "Q29999" },
    { name: "New Caledonia", code: "nc", flag: "https://flagcdn.com/w320/nc.png", wikidataId: "Q33788" },
    { name: "New Zealand", code: "nz", flag: "https://flagcdn.com/w320/nz.png", wikidataId: "Q664" },
    { name: "Nicaragua", code: "ni", flag: "https://flagcdn.com/w320/ni.png", wikidataId: "Q811" },
    { name: "Niger", code: "ne", flag: "https://flagcdn.com/w320/ne.png", wikidataId: "Q1032" },
    { name: "Nigeria", code: "ng", flag: "https://flagcdn.com/w320/ng.png", wikidataId: "Q1033" },
    { name: "Niue", code: "nu", flag: "https://flagcdn.com/w320/nu.png", wikidataId: "Q34020" },
    { name: "Norfolk Island", code: "nf", flag: "https://flagcdn.com/w320/nf.png", wikidataId: "Q31057" },
    { name: "North Korea", code: "kp", flag: "https://flagcdn.com/w320/kp.png", wikidataId: "Q423" },
    { name: "North Macedonia", code: "mk", flag: "https://flagcdn.com/w320/mk.png", wikidataId: "Q221" },
    { name: "Northern Mariana Islands", code: "mp", flag: "https://flagcdn.com/w320/mp.png", wikidataId: "Q16644" },
    { name: "Norway", code: "no", flag: "https://flagcdn.com/w320/no.png", wikidataId: "Q20" },
    { name: "Oman", code: "om", flag: "https://flagcdn.com/w320/om.png", wikidataId: "Q842" },
    { name: "Pakistan", code: "pk", flag: "https://flagcdn.com/w320/pk.png", wikidataId: "Q843" },
    { name: "Palau", code: "pw", flag: "https://flagcdn.com/w320/pw.png", wikidataId: "Q695" },
    { name: "Palestine, State of", code: "ps", flag: "https://flagcdn.com/w320/ps.png", wikidataId: "Q219060" },
    { name: "Panama", code: "pa", flag: "https://flagcdn.com/w320/pa.png", wikidataId: "Q804" },
    { name: "Papua New Guinea", code: "pg", flag: "https://flagcdn.com/w320/pg.png", wikidataId: "Q691" },
    { name: "Paraguay", code: "py", flag: "https://flagcdn.com/w320/py.png", wikidataId: "Q733" },
    { name: "Peru", code: "pe", flag: "https://flagcdn.com/w320/pe.png", wikidataId: "Q419" },
    { name: "Philippines", code: "ph", flag: "https://flagcdn.com/w320/ph.png", wikidataId: "Q928" },
    { name: "Pitcairn", code: "pn", flag: "https://flagcdn.com/w320/pn.png", wikidataId: "Q35672" },
    { name: "Poland", code: "pl", flag: "https://flagcdn.com/w320/pl.png", wikidataId: "Q36" },
    { name: "Portugal", code: "pt", flag: "https://flagcdn.com/w320/pt.png", wikidataId: "Q45" },
    { name: "Puerto Rico", code: "pr", flag: "https://flagcdn.com/w320/pr.png", wikidataId: "Q1183" },
    { name: "Qatar", code: "qa", flag: "https://flagcdn.com/w320/qa.png", wikidataId: "Q846" },
    { name: "Romania", code: "ro", flag: "https://flagcdn.com/w320/ro.png", wikidataId: "Q218" },
    { name: "Russian Federation", code: "ru", flag: "https://flagcdn.com/w320/ru.png", wikidataId: "Q159" },
    { name: "Rwanda", code: "rw", flag: "https://flagcdn.com/w320/rw.png", wikidataId: "Q1037" },
    { name: "Réunion", code: "re", flag: "https://flagcdn.com/w320/re.png", wikidataId: "Q17070" },
    { name: "Saint Barthélemy", code: "bl", flag: "https://flagcdn.com/w320/bl.png", wikidataId: "Q25362" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", code: "sh", flag: "https://flagcdn.com/w320/sh.png", wikidataId: "Q192184" },
    { name: "Saint Kitts and Nevis", code: "kn", flag: "https://flagcdn.com/w320/kn.png", wikidataId: "Q763" },
    { name: "Saint Lucia", code: "lc", flag: "https://flagcdn.com/w320/lc.png", wikidataId: "Q760" },
    { name: "Saint Martin (French part)", code: "mf", flag: "https://flagcdn.com/w320/mf.png", wikidataId: "Q126125" },
    { name: "Saint Pierre and Miquelon", code: "pm", flag: "https://flagcdn.com/w320/pm.png", wikidataId: "Q34617" },
    { name: "Saint Vincent and the Grenadines", code: "vc", flag: "https://flagcdn.com/w320/vc.png", wikidataId: "Q757" },
    { name: "Samoa", code: "ws", flag: "https://flagcdn.com/w320/ws.png", wikidataId: "Q683" },
    { name: "San Marino", code: "sm", flag: "https://flagcdn.com/w320/sm.png", wikidataId: "Q238" },
    { name: "Sao Tome and Principe", code: "st", flag: "https://flagcdn.com/w320/st.png", wikidataId: "Q1039" },
    { name: "Saudi Arabia", code: "sa", flag: "https://flagcdn.com/w320/sa.png", wikidataId: "Q851" },
    { name: "Senegal", code: "sn", flag: "https://flagcdn.com/w320/sn.png", wikidataId: "Q1041" },
    { name: "Serbia", code: "rs", flag: "https://flagcdn.com/w320/rs.png", wikidataId: "Q403" },
    { name: "Seychelles", code: "sc", flag: "https://flagcdn.com/w320/sc.png", wikidataId: "Q1042" },
    { name: "Sierra Leone", code: "sl", flag: "https://flagcdn.com/w320/sl.png", wikidataId: "Q1044" },
    { name: "Singapore", code: "sg", flag: "https://flagcdn.com/w320/sg.png", wikidataId: "Q334" },
    { name: "Sint Maarten (Dutch part)", code: "sx", flag: "https://flagcdn.com/w320/sx.png", wikidataId: "Q26273" },
    { name: "Slovakia", code: "sk", flag: "https://flagcdn.com/w320/sk.png", wikidataId: "Q214" },
    { name: "Slovenia", code: "si", flag: "https://flagcdn.com/w320/si.png", wikidataId: "Q215" },
    { name: "Solomon Islands", code: "sb", flag: "https://flagcdn.com/w320/sb.png", wikidataId: "Q685" },
    { name: "Somalia", code: "so", flag: "https://flagcdn.com/w320/so.png", wikidataId: "Q1045" },
    { name: "South Africa", code: "za", flag: "https://flagcdn.com/w320/za.png", wikidataId: "Q258" },
    { name: "South Georgia and the South Sandwich Islands", code: "gs", flag: "https://flagcdn.com/w320/gs.png", wikidataId: "Q35086" },
    { name: "South Korea", code: "kr", flag: "https://flagcdn.com/w320/kr.png", wikidataId: "Q884" },
    { name: "South Sudan", code: "ss", flag: "https://flagcdn.com/w320/ss.png", wikidataId: "Q958" },
    { name: "Spain", code: "es", flag: "https://flagcdn.com/w320/es.png", wikidataId: "Q29" },
    { name: "Sri Lanka", code: "lk", flag: "https://flagcdn.com/w320/lk.png", wikidataId: "Q854" },
    { name: "Sudan", code: "sd", flag: "https://flagcdn.com/w320/sd.png", wikidataId: "Q1049" },
    { name: "Suriname", code: "sr", flag: "https://flagcdn.com/w320/sr.png", wikidataId: "Q730" },
    { name: "Svalbard and Jan Mayen", code: "sj", flag: "https://flagcdn.com/w320/sj.png", wikidataId: "Q842829" },
    { name: "Sweden", code: "se", flag: "https://flagcdn.com/w320/se.png", wikidataId: "Q34" },
    { name: "Switzerland", code: "ch", flag: "https://flagcdn.com/w320/ch.png", wikidataId: "Q39" },
    { name: "Syria", code: "sy", flag: "https://flagcdn.com/w320/sy.png", wikidataId: "Q858" },
    { name: "Taiwan", code: "tw", flag: "https://flagcdn.com/w320/tw.png", wikidataId: "Q865" },
    { name: "Tajikistan", code: "tj", flag: "https://flagcdn.com/w320/tj.png", wikidataId: "Q863" },
    { name: "Tanzania", code: "tz", flag: "https://flagcdn.com/w320/tz.png", wikidataId: "Q924" },
    { name: "Thailand", code: "th", flag: "https://flagcdn.com/w320/th.png", wikidataId: "Q869" },
    { name: "Timor-Leste", code: "tl", flag: "https://flagcdn.com/w320/tl.png", wikidataId: "Q574" },
    { name: "Togo", code: "tg", flag: "https://flagcdn.com/w320/tg.png", wikidataId: "Q945" },
    { name: "Tokelau", code: "tk", flag: "https://flagcdn.com/w320/tk.png", wikidataId: "Q36823" },
    { name: "Tonga", code: "to", flag: "https://flagcdn.com/w320/to.png", wikidataId: "Q678" },
    { name: "Trinidad and Tobago", code: "tt", flag: "https://flagcdn.com/w320/tt.png", wikidataId: "Q754" },
    { name: "Tunisia", code: "tn", flag: "https://flagcdn.com/w320/tn.png", wikidataId: "Q948" },
    { name: "Turkmenistan", code: "tm", flag: "https://flagcdn.com/w320/tm.png", wikidataId: "Q874" },
    { name: "Turks and Caicos Islands", code: "tc", flag: "https://flagcdn.com/w320/tc.png", wikidataId: "Q18221" },
    { name: "Tuvalu", code: "tv", flag: "https://flagcdn.com/w320/tv.png", wikidataId: "Q672" },
    { name: "Türkiye", code: "tr", flag: "https://flagcdn.com/w320/tr.png", wikidataId: "Q43" },
    { name: "Uganda", code: "ug", flag: "https://flagcdn.com/w320/ug.png", wikidataId: "Q1036" },
    { name: "Ukraine", code: "ua", flag: "https://flagcdn.com/w320/ua.png", wikidataId: "Q212" },
    { name: "United Arab Emirates", code: "ae", flag: "https://flagcdn.com/w320/ae.png", wikidataId: "Q878" },
    { name: "United Kingdom", code: "gb", flag: "https://flagcdn.com/w320/gb.png", wikidataId: "Q145" },
    { name: "United States", code: "us", flag: "https://flagcdn.com/w320/us.png", wikidataId: "Q30" },
    { name: "United States Minor Outlying Islands", code: "um", flag: "https://flagcdn.com/w320/um.png", wikidataId: "Q16645" },
    { name: "Uruguay", code: "uy", flag: "https://flagcdn.com/w320/uy.png", wikidataId: "Q77" },
    { name: "Uzbekistan", code: "uz", flag: "https://flagcdn.com/w320/uz.png", wikidataId: "Q265" },
    { name: "Vanuatu", code: "vu", flag: "https://flagcdn.com/w320/vu.png", wikidataId: "Q686" },
    { name: "Venezuela", code: "ve", flag: "https://flagcdn.com/w320/ve.png", wikidataId: "Q717" },
    { name: "Vietnam", code: "vn", flag: "https://flagcdn.com/w320/vn.png", wikidataId: "Q881" },
    { name: "Virgin Islands, British", code: "vg", flag: "https://flagcdn.com/w320/vg.png", wikidataId: "Q25305" },
    { name: "Virgin Islands, U.S.", code: "vi", flag: "https://flagcdn.com/w320/vi.png", wikidataId: "Q11703" },
    { name: "Wallis and Futuna", code: "wf", flag: "https://flagcdn.com/w320/wf.png", wikidataId: "Q35555" },
    { name: "Western Sahara", code: "eh", flag: "https://flagcdn.com/w320/eh.png", wikidataId: "Q40362" },
    { name: "Yemen", code: "ye", flag: "https://flagcdn.com/w320/ye.png", wikidataId: "Q805" },
    { name: "Zambia", code: "zm", flag: "https://flagcdn.com/w320/zm.png", wikidataId: "Q953" },
    { name: "Zimbabwe", code: "zw", flag: "https://flagcdn.com/w320/zw.png", wikidataId: "Q954" },
    { name: "Åland Islands", code: "ax", flag: "https://flagcdn.com/w320/ax.png", wikidataId: "Q5689" },
];