// countries.ts
export interface Country {
    name: string;
    code: string;
    flag: string;
}

export const countries: Country[] = [
    { name: "Afghanistan", code: "af", flag: "https://flagcdn.com/w320/af.png" },
    { name: "Albania", code: "al", flag: "https://flagcdn.com/w320/al.png" },
    { name: "Algeria", code: "dz", flag: "https://flagcdn.com/w320/dz.png" },
    { name: "American Samoa", code: "as", flag: "https://flagcdn.com/w320/as.png" },
    { name: "Andorra", code: "ad", flag: "https://flagcdn.com/w320/ad.png" },
    { name: "Angola", code: "ao", flag: "https://flagcdn.com/w320/ao.png" },
    { name: "Anguilla", code: "ai", flag: "https://flagcdn.com/w320/ai.png" },
    { name: "Antarctica", code: "aq", flag: "https://flagcdn.com/w320/aq.png" },
    { name: "Antigua and Barbuda", code: "ag", flag: "https://flagcdn.com/w320/ag.png" },
    { name: "Argentina", code: "ar", flag: "https://flagcdn.com/w320/ar.png" },
    { name: "Armenia", code: "am", flag: "https://flagcdn.com/w320/am.png" },
    { name: "Aruba", code: "aw", flag: "https://flagcdn.com/w320/aw.png" },
    { name: "Australia", code: "au", flag: "https://flagcdn.com/w320/au.png" },
    { name: "Austria", code: "at", flag: "https://flagcdn.com/w320/at.png" },
    { name: "Azerbaijan", code: "az", flag: "https://flagcdn.com/w320/az.png" },
    { name: "Bahamas", code: "bs", flag: "https://flagcdn.com/w320/bs.png" },
    { name: "Bahrain", code: "bh", flag: "https://flagcdn.com/w320/bh.png" },
    { name: "Bangladesh", code: "bd", flag: "https://flagcdn.com/w320/bd.png" },
    { name: "Barbados", code: "bb", flag: "https://flagcdn.com/w320/bb.png" },
    { name: "Belarus", code: "by", flag: "https://flagcdn.com/w320/by.png" },
    { name: "Belgium", code: "be", flag: "https://flagcdn.com/w320/be.png" },
    { name: "Belize", code: "bz", flag: "https://flagcdn.com/w320/bz.png" },
    { name: "Benin", code: "bj", flag: "https://flagcdn.com/w320/bj.png" },
    { name: "Bermuda", code: "bm", flag: "https://flagcdn.com/w320/bm.png" },
    { name: "Bhutan", code: "bt", flag: "https://flagcdn.com/w320/bt.png" },
    { name: "Bolivia", code: "bo", flag: "https://flagcdn.com/w320/bo.png" },
    { name: "Bonaire, Sint Eustatius and Saba", code: "bq", flag: "https://flagcdn.com/w320/bq.png" },
    { name: "Bosnia and Herzegovina", code: "ba", flag: "https://flagcdn.com/w320/ba.png" },
    { name: "Botswana", code: "bw", flag: "https://flagcdn.com/w320/bw.png" },
    { name: "Bouvet Island", code: "bv", flag: "https://flagcdn.com/w320/bv.png" },
    { name: "Brazil", code: "br", flag: "https://flagcdn.com/w320/br.png" },
    { name: "British Indian Ocean Territory", code: "io", flag: "https://flagcdn.com/w320/io.png" },
    { name: "Brunei Darussalam", code: "bn", flag: "https://flagcdn.com/w320/bn.png" },
    { name: "Bulgaria", code: "bg", flag: "https://flagcdn.com/w320/bg.png" },
    { name: "Burkina Faso", code: "bf", flag: "https://flagcdn.com/w320/bf.png" },
    { name: "Burundi", code: "bi", flag: "https://flagcdn.com/w320/bi.png" },
    { name: "Cabo Verde", code: "cv", flag: "https://flagcdn.com/w320/cv.png" },
    { name: "Cambodia", code: "kh", flag: "https://flagcdn.com/w320/kh.png" },
    { name: "Cameroon", code: "cm", flag: "https://flagcdn.com/w320/cm.png" },
    { name: "Canada", code: "ca", flag: "https://flagcdn.com/w320/ca.png" },
    { name: "Cayman Islands", code: "ky", flag: "https://flagcdn.com/w320/ky.png" },
    { name: "Central African Republic", code: "cf", flag: "https://flagcdn.com/w320/cf.png" },
    { name: "Chad", code: "td", flag: "https://flagcdn.com/w320/td.png" },
    { name: "Chile", code: "cl", flag: "https://flagcdn.com/w320/cl.png" },
    { name: "China", code: "cn", flag: "https://flagcdn.com/w320/cn.png" },
    { name: "Christmas Island", code: "cx", flag: "https://flagcdn.com/w320/cx.png" },
    { name: "Cocos (Keeling) Islands", code: "cc", flag: "https://flagcdn.com/w320/cc.png" },
    { name: "Colombia", code: "co", flag: "https://flagcdn.com/w320/co.png" },
    { name: "Comoros", code: "km", flag: "https://flagcdn.com/w320/km.png" },
    { name: "Congo", code: "cg", flag: "https://flagcdn.com/w320/cg.png" },
    { name: "Congo, The Democratic Republic of the", code: "cd", flag: "https://flagcdn.com/w320/cd.png" },
    { name: "Cook Islands", code: "ck", flag: "https://flagcdn.com/w320/ck.png" },
    { name: "Costa Rica", code: "cr", flag: "https://flagcdn.com/w320/cr.png" },
    { name: "Croatia", code: "hr", flag: "https://flagcdn.com/w320/hr.png" },
    { name: "Cuba", code: "cu", flag: "https://flagcdn.com/w320/cu.png" },
    { name: "Curaçao", code: "cw", flag: "https://flagcdn.com/w320/cw.png" },
    { name: "Cyprus", code: "cy", flag: "https://flagcdn.com/w320/cy.png" },
    { name: "Czechia", code: "cz", flag: "https://flagcdn.com/w320/cz.png" },
    { name: "Côte d'Ivoire", code: "ci", flag: "https://flagcdn.com/w320/ci.png" },
    { name: "Denmark", code: "dk", flag: "https://flagcdn.com/w320/dk.png" },
    { name: "Djibouti", code: "dj", flag: "https://flagcdn.com/w320/dj.png" },
    { name: "Dominica", code: "dm", flag: "https://flagcdn.com/w320/dm.png" },
    { name: "Dominican Republic", code: "do", flag: "https://flagcdn.com/w320/do.png" },
    { name: "Ecuador", code: "ec", flag: "https://flagcdn.com/w320/ec.png" },
    { name: "Egypt", code: "eg", flag: "https://flagcdn.com/w320/eg.png" },
    { name: "El Salvador", code: "sv", flag: "https://flagcdn.com/w320/sv.png" },
    { name: "Equatorial Guinea", code: "gq", flag: "https://flagcdn.com/w320/gq.png" },
    { name: "Eritrea", code: "er", flag: "https://flagcdn.com/w320/er.png" },
    { name: "Estonia", code: "ee", flag: "https://flagcdn.com/w320/ee.png" },
    { name: "Eswatini", code: "sz", flag: "https://flagcdn.com/w320/sz.png" },
    { name: "Ethiopia", code: "et", flag: "https://flagcdn.com/w320/et.png" },
    { name: "Falkland Islands (Malvinas)", code: "fk", flag: "https://flagcdn.com/w320/fk.png" },
    { name: "Faroe Islands", code: "fo", flag: "https://flagcdn.com/w320/fo.png" },
    { name: "Fiji", code: "fj", flag: "https://flagcdn.com/w320/fj.png" },
    { name: "Finland", code: "fi", flag: "https://flagcdn.com/w320/fi.png" },
    { name: "France", code: "fr", flag: "https://flagcdn.com/w320/fr.png" },
    { name: "French Guiana", code: "gf", flag: "https://flagcdn.com/w320/gf.png" },
    { name: "French Polynesia", code: "pf", flag: "https://flagcdn.com/w320/pf.png" },
    { name: "French Southern Territories", code: "tf", flag: "https://flagcdn.com/w320/tf.png" },
    { name: "Gabon", code: "ga", flag: "https://flagcdn.com/w320/ga.png" },
    { name: "Gambia", code: "gm", flag: "https://flagcdn.com/w320/gm.png" },
    { name: "Georgia", code: "ge", flag: "https://flagcdn.com/w320/ge.png" },
    { name: "Germany", code: "de", flag: "https://flagcdn.com/w320/de.png" },
    { name: "Ghana", code: "gh", flag: "https://flagcdn.com/w320/gh.png" },
    { name: "Gibraltar", code: "gi", flag: "https://flagcdn.com/w320/gi.png" },
    { name: "Greece", code: "gr", flag: "https://flagcdn.com/w320/gr.png" },
    { name: "Greenland", code: "gl", flag: "https://flagcdn.com/w320/gl.png" },
    { name: "Grenada", code: "gd", flag: "https://flagcdn.com/w320/gd.png" },
    { name: "Guadeloupe", code: "gp", flag: "https://flagcdn.com/w320/gp.png" },
    { name: "Guam", code: "gu", flag: "https://flagcdn.com/w320/gu.png" },
    { name: "Guatemala", code: "gt", flag: "https://flagcdn.com/w320/gt.png" },
    { name: "Guernsey", code: "gg", flag: "https://flagcdn.com/w320/gg.png" },
    { name: "Guinea", code: "gn", flag: "https://flagcdn.com/w320/gn.png" },
    { name: "Guinea-Bissau", code: "gw", flag: "https://flagcdn.com/w320/gw.png" },
    { name: "Guyana", code: "gy", flag: "https://flagcdn.com/w320/gy.png" },
    { name: "Haiti", code: "ht", flag: "https://flagcdn.com/w320/ht.png" },
    { name: "Heard Island and McDonald Islands", code: "hm", flag: "https://flagcdn.com/w320/hm.png" },
    { name: "Holy See (Vatican City State)", code: "va", flag: "https://flagcdn.com/w320/va.png" },
    { name: "Honduras", code: "hn", flag: "https://flagcdn.com/w320/hn.png" },
    { name: "Hong Kong", code: "hk", flag: "https://flagcdn.com/w320/hk.png" },
    { name: "Hungary", code: "hu", flag: "https://flagcdn.com/w320/hu.png" },
    { name: "Iceland", code: "is", flag: "https://flagcdn.com/w320/is.png" },
    { name: "India", code: "in", flag: "https://flagcdn.com/w320/in.png" },
    { name: "Indonesia", code: "id", flag: "https://flagcdn.com/w320/id.png" },
    { name: "Iran", code: "ir", flag: "https://flagcdn.com/w320/ir.png" },
    { name: "Iraq", code: "iq", flag: "https://flagcdn.com/w320/iq.png" },
    { name: "Ireland", code: "ie", flag: "https://flagcdn.com/w320/ie.png" },
    { name: "Isle of Man", code: "im", flag: "https://flagcdn.com/w320/im.png" },
    { name: "Israel", code: "il", flag: "https://flagcdn.com/w320/il.png" },
    { name: "Italy", code: "it", flag: "https://flagcdn.com/w320/it.png" },
    { name: "Jamaica", code: "jm", flag: "https://flagcdn.com/w320/jm.png" },
    { name: "Japan", code: "jp", flag: "https://flagcdn.com/w320/jp.png" },
    { name: "Jersey", code: "je", flag: "https://flagcdn.com/w320/je.png" },
    { name: "Jordan", code: "jo", flag: "https://flagcdn.com/w320/jo.png" },
    { name: "Kazakhstan", code: "kz", flag: "https://flagcdn.com/w320/kz.png" },
    { name: "Kenya", code: "ke", flag: "https://flagcdn.com/w320/ke.png" },
    { name: "Kiribati", code: "ki", flag: "https://flagcdn.com/w320/ki.png" },
    { name: "Kuwait", code: "kw", flag: "https://flagcdn.com/w320/kw.png" },
    { name: "Kyrgyzstan", code: "kg", flag: "https://flagcdn.com/w320/kg.png" },
    { name: "Laos", code: "la", flag: "https://flagcdn.com/w320/la.png" },
    { name: "Latvia", code: "lv", flag: "https://flagcdn.com/w320/lv.png" },
    { name: "Lebanon", code: "lb", flag: "https://flagcdn.com/w320/lb.png" },
    { name: "Lesotho", code: "ls", flag: "https://flagcdn.com/w320/ls.png" },
    { name: "Liberia", code: "lr", flag: "https://flagcdn.com/w320/lr.png" },
    { name: "Libya", code: "ly", flag: "https://flagcdn.com/w320/ly.png" },
    { name: "Liechtenstein", code: "li", flag: "https://flagcdn.com/w320/li.png" },
    { name: "Lithuania", code: "lt", flag: "https://flagcdn.com/w320/lt.png" },
    { name: "Luxembourg", code: "lu", flag: "https://flagcdn.com/w320/lu.png" },
    { name: "Macao", code: "mo", flag: "https://flagcdn.com/w320/mo.png" },
    { name: "Madagascar", code: "mg", flag: "https://flagcdn.com/w320/mg.png" },
    { name: "Malawi", code: "mw", flag: "https://flagcdn.com/w320/mw.png" },
    { name: "Malaysia", code: "my", flag: "https://flagcdn.com/w320/my.png" },
    { name: "Maldives", code: "mv", flag: "https://flagcdn.com/w320/mv.png" },
    { name: "Mali", code: "ml", flag: "https://flagcdn.com/w320/ml.png" },
    { name: "Malta", code: "mt", flag: "https://flagcdn.com/w320/mt.png" },
    { name: "Marshall Islands", code: "mh", flag: "https://flagcdn.com/w320/mh.png" },
    { name: "Martinique", code: "mq", flag: "https://flagcdn.com/w320/mq.png" },
    { name: "Mauritania", code: "mr", flag: "https://flagcdn.com/w320/mr.png" },
    { name: "Mauritius", code: "mu", flag: "https://flagcdn.com/w320/mu.png" },
    { name: "Mayotte", code: "yt", flag: "https://flagcdn.com/w320/yt.png" },
    { name: "Mexico", code: "mx", flag: "https://flagcdn.com/w320/mx.png" },
    { name: "Micronesia, Federated States of", code: "fm", flag: "https://flagcdn.com/w320/fm.png" },
    { name: "Moldova", code: "md", flag: "https://flagcdn.com/w320/md.png" },
    { name: "Monaco", code: "mc", flag: "https://flagcdn.com/w320/mc.png" },
    { name: "Mongolia", code: "mn", flag: "https://flagcdn.com/w320/mn.png" },
    { name: "Montenegro", code: "me", flag: "https://flagcdn.com/w320/me.png" },
    { name: "Montserrat", code: "ms", flag: "https://flagcdn.com/w320/ms.png" },
    { name: "Morocco", code: "ma", flag: "https://flagcdn.com/w320/ma.png" },
    { name: "Mozambique", code: "mz", flag: "https://flagcdn.com/w320/mz.png" },
    { name: "Myanmar", code: "mm", flag: "https://flagcdn.com/w320/mm.png" },
    { name: "Namibia", code: "na", flag: "https://flagcdn.com/w320/na.png" },
    { name: "Nauru", code: "nr", flag: "https://flagcdn.com/w320/nr.png" },
    { name: "Nepal", code: "np", flag: "https://flagcdn.com/w320/np.png" },
    { name: "Netherlands", code: "nl", flag: "https://flagcdn.com/w320/nl.png" },
    { name: "New Caledonia", code: "nc", flag: "https://flagcdn.com/w320/nc.png" },
    { name: "New Zealand", code: "nz", flag: "https://flagcdn.com/w320/nz.png" },
    { name: "Nicaragua", code: "ni", flag: "https://flagcdn.com/w320/ni.png" },
    { name: "Niger", code: "ne", flag: "https://flagcdn.com/w320/ne.png" },
    { name: "Nigeria", code: "ng", flag: "https://flagcdn.com/w320/ng.png" },
    { name: "Niue", code: "nu", flag: "https://flagcdn.com/w320/nu.png" },
    { name: "Norfolk Island", code: "nf", flag: "https://flagcdn.com/w320/nf.png" },
    { name: "North Korea", code: "kp", flag: "https://flagcdn.com/w320/kp.png" },
    { name: "North Macedonia", code: "mk", flag: "https://flagcdn.com/w320/mk.png" },
    { name: "Northern Mariana Islands", code: "mp", flag: "https://flagcdn.com/w320/mp.png" },
    { name: "Norway", code: "no", flag: "https://flagcdn.com/w320/no.png" },
    { name: "Oman", code: "om", flag: "https://flagcdn.com/w320/om.png" },
    { name: "Pakistan", code: "pk", flag: "https://flagcdn.com/w320/pk.png" },
    { name: "Palau", code: "pw", flag: "https://flagcdn.com/w320/pw.png" },
    { name: "Palestine, State of", code: "ps", flag: "https://flagcdn.com/w320/ps.png" },
    { name: "Panama", code: "pa", flag: "https://flagcdn.com/w320/pa.png" },
    { name: "Papua New Guinea", code: "pg", flag: "https://flagcdn.com/w320/pg.png" },
    { name: "Paraguay", code: "py", flag: "https://flagcdn.com/w320/py.png" },
    { name: "Peru", code: "pe", flag: "https://flagcdn.com/w320/pe.png" },
    { name: "Philippines", code: "ph", flag: "https://flagcdn.com/w320/ph.png" },
    { name: "Pitcairn", code: "pn", flag: "https://flagcdn.com/w320/pn.png" },
    { name: "Poland", code: "pl", flag: "https://flagcdn.com/w320/pl.png" },
    { name: "Portugal", code: "pt", flag: "https://flagcdn.com/w320/pt.png" },
    { name: "Puerto Rico", code: "pr", flag: "https://flagcdn.com/w320/pr.png" },
    { name: "Qatar", code: "qa", flag: "https://flagcdn.com/w320/qa.png" },
    { name: "Romania", code: "ro", flag: "https://flagcdn.com/w320/ro.png" },
    { name: "Russian Federation", code: "ru", flag: "https://flagcdn.com/w320/ru.png" },
    { name: "Rwanda", code: "rw", flag: "https://flagcdn.com/w320/rw.png" },
    { name: "Réunion", code: "re", flag: "https://flagcdn.com/w320/re.png" },
    { name: "Saint Barthélemy", code: "bl", flag: "https://flagcdn.com/w320/bl.png" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", code: "sh", flag: "https://flagcdn.com/w320/sh.png" },
    { name: "Saint Kitts and Nevis", code: "kn", flag: "https://flagcdn.com/w320/kn.png" },
    { name: "Saint Lucia", code: "lc", flag: "https://flagcdn.com/w320/lc.png" },
    { name: "Saint Martin (French part)", code: "mf", flag: "https://flagcdn.com/w320/mf.png" },
    { name: "Saint Pierre and Miquelon", code: "pm", flag: "https://flagcdn.com/w320/pm.png" },
    { name: "Saint Vincent and the Grenadines", code: "vc", flag: "https://flagcdn.com/w320/vc.png" },
    { name: "Samoa", code: "ws", flag: "https://flagcdn.com/w320/ws.png" },
    { name: "San Marino", code: "sm", flag: "https://flagcdn.com/w320/sm.png" },
    { name: "Sao Tome and Principe", code: "st", flag: "https://flagcdn.com/w320/st.png" },
    { name: "Saudi Arabia", code: "sa", flag: "https://flagcdn.com/w320/sa.png" },
    { name: "Senegal", code: "sn", flag: "https://flagcdn.com/w320/sn.png" },
    { name: "Serbia", code: "rs", flag: "https://flagcdn.com/w320/rs.png" },
    { name: "Seychelles", code: "sc", flag: "https://flagcdn.com/w320/sc.png" },
    { name: "Sierra Leone", code: "sl", flag: "https://flagcdn.com/w320/sl.png" },
    { name: "Singapore", code: "sg", flag: "https://flagcdn.com/w320/sg.png" },
    { name: "Sint Maarten (Dutch part)", code: "sx", flag: "https://flagcdn.com/w320/sx.png" },
    { name: "Slovakia", code: "sk", flag: "https://flagcdn.com/w320/sk.png" },
    { name: "Slovenia", code: "si", flag: "https://flagcdn.com/w320/si.png" },
    { name: "Solomon Islands", code: "sb", flag: "https://flagcdn.com/w320/sb.png" },
    { name: "Somalia", code: "so", flag: "https://flagcdn.com/w320/so.png" },
    { name: "South Africa", code: "za", flag: "https://flagcdn.com/w320/za.png" },
    { name: "South Georgia and the South Sandwich Islands", code: "gs", flag: "https://flagcdn.com/w320/gs.png" },
    { name: "South Korea", code: "kr", flag: "https://flagcdn.com/w320/kr.png" },
    { name: "South Sudan", code: "ss", flag: "https://flagcdn.com/w320/ss.png" },
    { name: "Spain", code: "es", flag: "https://flagcdn.com/w320/es.png" },
    { name: "Sri Lanka", code: "lk", flag: "https://flagcdn.com/w320/lk.png" },
    { name: "Sudan", code: "sd", flag: "https://flagcdn.com/w320/sd.png" },
    { name: "Suriname", code: "sr", flag: "https://flagcdn.com/w320/sr.png" },
    { name: "Svalbard and Jan Mayen", code: "sj", flag: "https://flagcdn.com/w320/sj.png" },
    { name: "Sweden", code: "se", flag: "https://flagcdn.com/w320/se.png" },
    { name: "Switzerland", code: "ch", flag: "https://flagcdn.com/w320/ch.png" },
    { name: "Syria", code: "sy", flag: "https://flagcdn.com/w320/sy.png" },
    { name: "Taiwan", code: "tw", flag: "https://flagcdn.com/w320/tw.png" },
    { name: "Tajikistan", code: "tj", flag: "https://flagcdn.com/w320/tj.png" },
    { name: "Tanzania", code: "tz", flag: "https://flagcdn.com/w320/tz.png" },
    { name: "Thailand", code: "th", flag: "https://flagcdn.com/w320/th.png" },
    { name: "Timor-Leste", code: "tl", flag: "https://flagcdn.com/w320/tl.png" },
    { name: "Togo", code: "tg", flag: "https://flagcdn.com/w320/tg.png" },
    { name: "Tokelau", code: "tk", flag: "https://flagcdn.com/w320/tk.png" },
    { name: "Tonga", code: "to", flag: "https://flagcdn.com/w320/to.png" },
    { name: "Trinidad and Tobago", code: "tt", flag: "https://flagcdn.com/w320/tt.png" },
    { name: "Tunisia", code: "tn", flag: "https://flagcdn.com/w320/tn.png" },
    { name: "Turkmenistan", code: "tm", flag: "https://flagcdn.com/w320/tm.png" },
    { name: "Turks and Caicos Islands", code: "tc", flag: "https://flagcdn.com/w320/tc.png" },
    { name: "Tuvalu", code: "tv", flag: "https://flagcdn.com/w320/tv.png" },
    { name: "Türkiye", code: "tr", flag: "https://flagcdn.com/w320/tr.png" },
    { name: "Uganda", code: "ug", flag: "https://flagcdn.com/w320/ug.png" },
    { name: "Ukraine", code: "ua", flag: "https://flagcdn.com/w320/ua.png" },
    { name: "United Arab Emirates", code: "ae", flag: "https://flagcdn.com/w320/ae.png" },
    { name: "United Kingdom", code: "gb", flag: "https://flagcdn.com/w320/gb.png" },
    { name: "United States", code: "us", flag: "https://flagcdn.com/w320/us.png" },
    { name: "United States Minor Outlying Islands", code: "um", flag: "https://flagcdn.com/w320/um.png" },
    { name: "Uruguay", code: "uy", flag: "https://flagcdn.com/w320/uy.png" },
    { name: "Uzbekistan", code: "uz", flag: "https://flagcdn.com/w320/uz.png" },
    { name: "Vanuatu", code: "vu", flag: "https://flagcdn.com/w320/vu.png" },
    { name: "Venezuela", code: "ve", flag: "https://flagcdn.com/w320/ve.png" },
    { name: "Vietnam", code: "vn", flag: "https://flagcdn.com/w320/vn.png" },
    { name: "Virgin Islands, British", code: "vg", flag: "https://flagcdn.com/w320/vg.png" },
    { name: "Virgin Islands, U.S.", code: "vi", flag: "https://flagcdn.com/w320/vi.png" },
    { name: "Wallis and Futuna", code: "wf", flag: "https://flagcdn.com/w320/wf.png" },
    { name: "Western Sahara", code: "eh", flag: "https://flagcdn.com/w320/eh.png" },
    { name: "Yemen", code: "ye", flag: "https://flagcdn.com/w320/ye.png" },
    { name: "Zambia", code: "zm", flag: "https://flagcdn.com/w320/zm.png" },
    { name: "Zimbabwe", code: "zw", flag: "https://flagcdn.com/w320/zw.png" },
    { name: "Åland Islands", code: "ax", flag: "https://flagcdn.com/w320/ax.png" },
];